version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:      
      DB_HOST : localhost
      DB_PORT : 5432
      DB_USER : example_user
      DB_PASSWORD : Sup3rS3cret
      DB_NAME : example_db
      JWT_SECRET : your_jwt_secret
      API_LAYER_KEY : 0bWeisRWoLj3UdXt3MXMSMWptYFIpQfS
      GEMINI_API_KEY : AIzaSyDa1wojqyNbwIDxScfkXBCL6arRU7b2gzQ
      
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: Sup3rS3cret
    ports:
      - "5432:5432"
